### PR TITLE
feat: show a better error message for missing nginx files

### LINKED ISSUE #30: Better error message when Nginx config is not found
Hey!

Right now I'm getting the following error when I run `rhit` without Nginx set up:

```
Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

I think we can make this error message more informative.

I would like to submit a PR if applicable 🐻

### PR DESCRIPTION
**Pull request by orhun**
Before:

```
Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

After:

```
Following path(s) not found: ["/var/log/nginx"] (do you have nginx set up?)
Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

Some things to note:

- behavior change: `log_mem(Level::Info);` is being called in the case of error, I guess that's not a problem.
- stderr logging: I tried to use `error!` but logs didn't show up, so I went with `eprintln!`

closes #30

### CODE REVIEW

**Comment by Canop** [comment]
It's quite good but the "do you have nginx set up?" message should not be displayed when the user asked for a specific path, like

    rhit files-I-copied-from-my-server.log

**Comment by orhun** [comment]
Ah I see, makes sense. My question is do you prefer to show that message if the default path (`/var/log/nginx`) is used or should we remove it?

**Comment by Canop** [comment]
The message is a nice touch, it should be displayed when relevant. Maybe make it even clearer, like "(which is the default location for ngnix log files)".

**Comment by Canop** [comment]
Are you going to push another commit it or would you prefer me to finish that ?

**Comment by orhun** [comment]
Yup I will finish this!

**Comment by orhun** [comment]
Just pushed 60e50c1b4ed7a4e3c52052cc56a2ed929e3ba127

So the following error message shown when `/var/log/nginx` is used:

```
Following path(s) not found: ["/var/log/nginx"] (which is the default location for nginx files, do you have nginx set up?)
Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**Comment by Canop** [comment]
I ended up doing some other changes, because of this case:

    rhit existing-file.log non-existing-file.log
    
As it wasn't correct to say that both files weren't found, I added the missing path in the error.

**Pull request merged**
